"""empty message

Revision ID: c653db1ba640
Revises: 750cdc702a91
Create Date: 2022-08-03 17:26:00.288613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c653db1ba640'
down_revision = '750cdc702a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'init_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coupon', 'remaining_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'remaining_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coupon', 'init_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
